[package]
name = "note_gui"
version = "0.1.1"
description = "Локальная записная книжка"
authors = ["note-gui"]
edition = "2021"

[lib]
name = "note_gui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
rusqlite = { version = "0.32", features = ["bundled"] }
notify = "6"
sha2 = "0.10"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
regex = "1"
url = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
